"""add segments form_normalized

Revision ID: 17b77d38125c
Revises: 3f8eb9f392f5
Create Date: 2026-10-08 08:39:38.348590

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.arabic import normalize_arabic

# revision identifiers, used by Alembic.
revision: str = "17b77d38125c"
down_revision: str | Sequence[str] | None = "3f8eb9f392f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("segments", sa.Column("form_normalized", sa.Text(), nullable=True))
    # Backfill already-loaded segments in one statement; normalization is done in Python so it
    # matches what the loader writes
    connection = op.get_bind()
    rows = connection.execute(sa.text("SELECT id, form FROM segments")).all()
    if rows:
        connection.execute(
            sa.text(
                "UPDATE segments SET form_normalized = v.form_normalized "
                "FROM unnest(CAST(:ids AS integer[]), CAST(:forms AS text[])) "
                "AS v(id, form_normalized) WHERE segments.id = v.id"
            ),
            {
                "ids": [id_ for id_, _ in rows],
                "forms": [normalize_arabic(form) for _, form in rows],
            },
        )
    op.alter_column("segments", "form_normalized", nullable=False)
    op.create_index(
        op.f("ix_segments_form_normalized"), "segments", ["form_normalized"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_segments_form_normalized"), table_name="segments")
    op.drop_column("segments", "form_normalized")
    # ### end Alembic commands ###
