"""add words split_normalized

Revision ID: fd6e48a7d821
Revises: 17b77d38125c
Create Date: 2026-10-08 08:48:21.868504

"""

import json
from collections.abc import Sequence
from itertools import groupby

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.scripts.morphology import split_vocative

# revision identifiers, used by Alembic.
revision: str = "fd6e48a7d821"
down_revision: str | Sequence[str] | None = "17b77d38125c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "words", sa.Column("split_normalized", postgresql.ARRAY(sa.Text()), nullable=True)
    )
    # Backfill already-loaded words in one statement, with the loader's own split function
    connection = op.get_bind()
    segments = connection.execute(
        sa.text(
            "SELECT word_id, form_normalized, kind, features FROM segments ORDER BY word_id, number"
        )
    ).mappings()
    words = [
        {"id": word_id, "split_normalized": split_vocative(list(rows))}
        for word_id, rows in groupby(segments, key=lambda row: row["word_id"])
    ]
    if words:
        connection.execute(
            sa.text(
                "UPDATE words SET split_normalized = v.split_normalized "
                "FROM jsonb_to_recordset(CAST(:words AS jsonb)) "
                "AS v(id integer, split_normalized text[]) WHERE words.id = v.id"
            ),
            {"words": json.dumps(words)},
        )
    op.alter_column("words", "split_normalized", nullable=False)
    op.create_index(
        "ix_words_split_normalized",
        "words",
        ["split_normalized"],
        unique=False,
        postgresql_using="gin",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_words_split_normalized", table_name="words", postgresql_using="gin")
    op.drop_column("words", "split_normalized")
    # ### end Alembic commands ###
