"""add surahs and ayas

Revision ID: 12b4331d0228
Revises:
Create Date: 2026-10-07 23:53:26.180601

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12b4331d0228"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "surahs",
        sa.Column("id", sa.SmallInteger(), autoincrement=False, nullable=False),
        sa.Column("name_arabic", sa.String(length=50), nullable=False),
        sa.Column("name_transliterated", sa.String(length=50), nullable=False),
        sa.Column("name_english", sa.String(length=100), nullable=False),
        sa.Column("revelation_type", sa.String(length=7), nullable=False),
        sa.Column("revelation_order", sa.SmallInteger(), nullable=False),
        sa.Column("aya_count", sa.SmallInteger(), nullable=False),
        sa.Column("has_basmala", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "revelation_type IN ('meccan', 'medinan')", name=op.f("ck_surahs_revelation_type")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_surahs")),
        sa.UniqueConstraint("revelation_order", name=op.f("uq_surahs_revelation_order")),
    )
    op.create_table(
        "ayas",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("surah_id", sa.SmallInteger(), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=False),
        sa.Column("text_simple", sa.Text(), nullable=False),
        sa.Column("text_uthmani", sa.Text(), nullable=False),
        sa.CheckConstraint("number >= 1", name=op.f("ck_ayas_number_positive")),
        sa.ForeignKeyConstraint(["surah_id"], ["surahs.id"], name=op.f("fk_ayas_surah_id_surahs")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ayas")),
        sa.UniqueConstraint("surah_id", "number", name=op.f("uq_ayas_surah_id_number")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ayas")
    op.drop_table("surahs")
    # ### end Alembic commands ###
