"""add words and segments

Revision ID: b5acc4770508
Revises: 12b4331d0228
Create Date: 2026-10-08 00:25:05.847583

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b5acc4770508"
down_revision: str | Sequence[str] | None = "12b4331d0228"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "words",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("aya_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=False),
        sa.Column("text_uthmani", sa.Text(), nullable=False),
        sa.Column("text_normalized", sa.Text(), nullable=False),
        sa.CheckConstraint("number >= 1", name=op.f("ck_words_number_positive")),
        sa.ForeignKeyConstraint(["aya_id"], ["ayas.id"], name=op.f("fk_words_aya_id_ayas")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_words")),
        sa.UniqueConstraint("aya_id", "number", name=op.f("uq_words_aya_id_number")),
    )
    op.create_index(op.f("ix_words_text_normalized"), "words", ["text_normalized"], unique=False)
    op.create_table(
        "segments",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("word_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.SmallInteger(), nullable=False),
        sa.Column("form", sa.Text(), nullable=False),
        sa.Column("pos", sa.String(length=1), nullable=False),
        sa.Column("kind", sa.String(length=6), nullable=False),
        sa.Column("root", sa.Text(), nullable=True),
        sa.Column("lemma", sa.Text(), nullable=True),
        sa.Column("verb_form", sa.SmallInteger(), nullable=True),
        sa.Column("mood", sa.Text(), nullable=True),
        sa.Column("family", sa.Text(), nullable=True),
        sa.Column("features", postgresql.ARRAY(sa.Text()), nullable=False),
        sa.CheckConstraint("kind IN ('prefix', 'stem', 'suffix')", name=op.f("ck_segments_kind")),
        sa.CheckConstraint("pos IN ('N', 'V', 'P')", name=op.f("ck_segments_pos")),
        sa.CheckConstraint("number >= 1", name=op.f("ck_segments_number_positive")),
        sa.ForeignKeyConstraint(["word_id"], ["words.id"], name=op.f("fk_segments_word_id_words")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_segments")),
        sa.UniqueConstraint("word_id", "number", name=op.f("uq_segments_word_id_number")),
    )
    op.create_index(
        "ix_segments_features", "segments", ["features"], unique=False, postgresql_using="gin"
    )
    op.create_index(op.f("ix_segments_lemma"), "segments", ["lemma"], unique=False)
    op.create_index(op.f("ix_segments_root"), "segments", ["root"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_segments_root"), table_name="segments")
    op.drop_index(op.f("ix_segments_lemma"), table_name="segments")
    op.drop_index("ix_segments_features", table_name="segments", postgresql_using="gin")
    op.drop_table("segments")
    op.drop_index(op.f("ix_words_text_normalized"), table_name="words")
    op.drop_table("words")
    # ### end Alembic commands ###
